<a href="https://colab.research.google.com/github/MrAlexBykov/MACHINE-LEARNING/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%9B%D0%B11_%D0%91%D0%B8%D0%BA%D0%BE%D0%B2_3_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div class="markdown-google-sans">

## <strong>Начало работы</strong>
</div>

Документ, который вы читаете, размещен не на статической веб-странице, а в интерактивной среде под названием <strong>блокнот Colab</strong>, позволяющей писать и выполнять код.

Например, вот <strong>ячейка</strong> с коротким скриптом Python, который позволяет рассчитать значение, выразить его в виде переменной и распечатать результат:

In [ ]:
#1 Створіть одновимірний масив (вектор) з парними числами від 2 до 20 та виведіть
# його значення
import numpy as np

even_numbers = np.arange(2, 21, 2)
even_numbers


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими
#дійсними числами від 0 до 1 та виведіть його значення.
import numpy as np

random_matrix = np.random.rand(3, 3)
random_matrix


array([[0.80140951, 0.50902251, 0.505963  ],
       [0.12639927, 0.42797657, 0.38237179],
       [0.11877661, 0.09101944, 0.65685684]])

In [ ]:
#3 Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
# 1 до 20 та виведіть його значення.
import numpy as np

random_integer_matrix = np.random.randint(1, 21, size=(3, 3))
random_integer_matrix


array([[11, 11, 17],
       [ 3, 12, 12],
       [18, 12,  7]])

In [ ]:
#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та знайдіть мінімальний елемент
import numpy as np

matrix = np.random.rand(4, 4)

min_element = np.min(matrix)

matrix, min_element


(array([[0.96008088, 0.85699476, 0.43773791, 0.47295107],
        [0.96316304, 0.79650799, 0.64184797, 0.38122748],
        [0.58015678, 0.59167146, 0.97924377, 0.06675203],
        [0.98049249, 0.43266483, 0.02464392, 0.57048473]]),
 0.024643923723658423)

In [ ]:
#5 Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими
# числами в діапазоні від 1 до 15 та виконайте на них поелементні операції додавання,
# віднімання та множення.
import numpy as np

array1 = np.random.randint(1, 16, size=7)
array2 = np.random.randint(1, 16, size=7)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

array1, array2, addition, subtraction, multiplication


(array([ 7,  4,  5,  1, 10,  3,  5]),
 array([ 7,  7, 12,  1, 12,  5, 13]),
 array([14, 11, 17,  2, 22,  8, 18]),
 array([ 0, -3, -7,  0, -2, -2, -8]),
 array([ 49,  28,  60,   1, 120,  15,  65]))

In [ ]:
#6 Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 3 до 30 та
# знайдіть їх добуток.
import numpy as np

matrix1 = np.random.randint(3, 31, size=(3, 3))
matrix2 = np.random.randint(3, 31, size=(3, 3))

matrix_product = np.dot(matrix1, matrix2)

matrix1, matrix2, matrix_product


(array([[13, 24, 29],
        [27, 27,  3],
        [26, 25, 22]]),
 array([[17, 16, 19],
        [20, 21,  4],
        [30,  3, 10]]),
 array([[1571,  799,  633],
        [1089, 1008,  651],
        [1602, 1007,  814]]))

In [ ]:
#7 Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 7 та перемножте їх між собою
import numpy as np

matrix1 = np.random.randint(1, 8, size=(4, 2))

matrix2 = np.random.randint(1, 8, size=(2, 5))

matrix_product = np.dot(matrix1, matrix2)

matrix1, matrix2, matrix_product


(array([[4, 4],
        [2, 5],
        [6, 5],
        [5, 6]]),
 array([[7, 4, 7, 5, 3],
        [2, 2, 2, 1, 3]]),
 array([[36, 24, 36, 24, 24],
        [24, 18, 24, 15, 21],
        [52, 34, 52, 35, 33],
        [47, 32, 47, 31, 33]]))

In [ ]:
#8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
# від 1 до 8 та знайдіть її обернену матрицю.
import numpy as np

matrix = np.random.randint(1, 9, size=(2, 2))

inverse_matrix = np.linalg.inv(matrix)

matrix, inverse_matrix



(array([[6, 4],
        [5, 8]]),
 array([[ 0.28571429, -0.14285714],
        [-0.17857143,  0.21428571]]))

In [ ]:
#9 Створіть матрицю розміром 2x3, заповніть її випадковими дійсними числами в
# діапазоні від 0 до 1 та транспонуйте її
import numpy as np

matrix = np.random.rand(2, 3)

transposed_matrix = np.transpose(matrix)

matrix, transposed_matrix


(array([[0.36543449, 0.28507241, 0.67508988],
        [0.32285908, 0.12662581, 0.23485068]]),
 array([[0.36543449, 0.32285908],
        [0.28507241, 0.12662581],
        [0.67508988, 0.23485068]]))

In [ ]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.
import numpy as np

matrix_shape = (3, 4)
vector_shape = (4, 1)

matrix = np.random.randint(1, 11, size=matrix_shape)
vector = np.random.randint(1, 11, size=vector_shape)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

product = np.dot(matrix, vector)

print("\nДобуток матриці на вектор:")
print(product)


Матриця:
[[ 5 10  9  2]
 [ 5  3  8  8]
 [ 9 10 10  1]]

Вектор:
[[ 9]
 [ 2]
 [10]
 [ 2]]

Добуток матриці на вектор:
[[159]
 [147]
 [203]]


In [ ]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
# випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
# діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

matrix_shape = (2, 3)
vector_shape = (3, 1)

matrix = np.random.rand(*matrix_shape)

vector = np.random.randint(1, 11, size=vector_shape)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)

product = np.dot(matrix, vector)

print("\nДобуток матриці на вектор:")
print(product)


Матриця:
[[0.98176366 0.25216915 0.29417632]
 [0.35405093 0.59121527 0.17277526]]

Вектор:
[[4]
 [6]
 [7]]

Добуток матриці на вектор:
[[7.49930384]
 [6.17292214]]


In [ ]:
#12 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть їхню суму.

import numpy as np

matrix_shape = (4, 4)

matrix1 = np.random.randint(1, 11, size=matrix_shape)
matrix2 = np.random.randint(1, 11, size=matrix_shape)

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

matrix_sum = matrix1 + matrix2

print("\nСума матриць:")
print(matrix_sum)


Перша матриця:
[[ 4  7 10 10]
 [ 2  7  4  3]
 [ 1  2  5  5]
 [ 9  5  8 10]]

Друга матриця:
[[8 9 1 7]
 [7 4 9 7]
 [7 2 6 7]
 [2 6 9 6]]

Сума матриць:
[[12 16 11 17]
 [ 9 11 13 10]
 [ 8  4 11 12]
 [11 11 17 16]]


In [ ]:
#13 Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в
#діапазоні від -1 до 1 та знайдіть їх добуток
import numpy as np

matrix_shape = (4, 4)

matrix1 = np.random.uniform(-1, 1, size=matrix_shape)
matrix2 = np.random.uniform(-1, 1, size=matrix_shape)

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

matrix_product = np.dot(matrix1, matrix2)

print("\nДобуток матриць:")
print(matrix_product)


Перша матриця:
[[ 0.93874832 -0.83138081 -0.64602183 -0.52207881]
 [ 0.04989924  0.26947509  0.92318119 -0.2914356 ]
 [ 0.5544335   0.50494744  0.19271339  0.68769017]
 [ 0.22020347 -0.03026575  0.30108844  0.25851283]]

Друга матриця:
[[-0.08580717 -0.32968835  0.8231193  -0.33147459]
 [ 0.4210676  -0.57786183 -0.26121982 -0.11253678]
 [-0.70144588 -0.31660879 -0.53055584  0.7972579 ]
 [ 0.35547314 -0.90109642  0.27021844 -0.58798082]]

Добуток матриць:
[[-0.1630545   0.84590838  1.19155034 -0.42568397]
 [-0.64197365 -0.20184627 -0.59786966  0.86050585]
 [ 0.27432001 -1.15527002  0.40804398 -0.49131213]
 [-0.15094184 -0.38338133  0.09927044  0.0184587 ]]


In [ ]:
#14 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
#діапазоні від -1 до 1 та знайдіть суму елементів матриці
import numpy as np


matrix_shape = (3, 3)
matrix = np.random.uniform(-1, 1, size=matrix_shape)
print("Матриця:")
print(matrix)
matrix_sum = np.sum(matrix)
print("\nСума елементів матриці:")
print(matrix_sum)


Матриця:
[[-0.61231224 -0.97757845  0.5629573 ]
 [-0.15719309 -0.6778557   0.22651161]
 [-0.58975208 -0.66368326  0.29909571]]

Сума елементів матриці:
-2.5898102006822996


In [ ]:
#15 Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
#діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів
#кожного рядка матриці.

import numpy as np

matrix_shape = (5, 5)
matrix = np.random.uniform(-0.5, 0.5, size=matrix_shape)
print("Матриця:")
print(matrix)
row_sums = np.sum(matrix, axis=1)

column_vector = row_sums.reshape(-1, 1)

print("\nВектор, що містить суму елементів кожного рядка:")
print(column_vector)


Матриця:
[[-0.21013037  0.27831389  0.29824597  0.28856313  0.27554131]
 [-0.14559074 -0.18068805 -0.15516216 -0.22668484  0.19871053]
 [ 0.46322829  0.25504187 -0.1019521  -0.24762996 -0.49763589]
 [-0.14094274 -0.48506794  0.17839439 -0.3780136   0.24013774]
 [-0.45748114 -0.22740343  0.16160815  0.27499031  0.41825437]]

Вектор, що містить суму елементів кожного рядка:
[[ 0.93053393]
 [-0.50941527]
 [-0.12894778]
 [-0.58549215]
 [ 0.16996826]]
